import { Inter } from "next/font/google";
import "./globals.css";
import ContextProvider from "@/Context/UserContext";
import CallContextProvider from "@/Context/CallContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CallContextProvider>
        <ContextProvider>
          <body className={inter.className}>{children}</body>
        </ContextProvider>
      </CallContextProvider>
    </html>
  );
}
